services:
  mock-oauth2-server:
    hostname: mock-oauth2-server
    image: ghcr.io/navikt/mock-oauth2-server:0.3.4
    ports:
      - "8888:8080"
    environment:
      JSON_CONFIG: '{
  "tokenCallbacks": [
    {
      "issuerId": "default",
      "requestMappings": [
        {
          "requestParam": "grant_type",
          "match": "authorization_code",
          "claims": {
            "NAVident": "H12345"
          }
        }
      ]
    }
  ]
}'
  spanner:
    hostname: spanner
    depends_on:
      - mock-oauth2-server
    restart: unless-stopped
    build: .
    ports:
      - "8080:8080"
    environment:
      AZURE_APP_WELL_KNOWN_URL: http://mock-oauth2-server:8080/default/.well-known/openid-configuration
      AZURE_APP_CLIENT_ID: foo
      AZURE_APP_CLIENT_SECRET: bar
      ISSUER: baz
      ACCEPTED_AUDIENCE: quoz
      SPLEIS_CLIENT_ID: foobar
      AUTHORIZATION_URL: http://localhost:8888/default/authorize
      DEVELOPMENT: true
      SPLEIS_API_URL: http://dummy
      SPARSOM_API_URL: http://dummy
      SPARSOM_CLIENT_ID: "test"
  audit.nais:
    image: balabit/syslog-ng:latest
    volumes:
      - ${PWD}/audit-test.conf:/etc/syslog-ng/syslog-ng.conf
