[versions]
jjwt = "0.13.0"
konfig = "1.6.10.0"
logback = "1.6.1"
logback-syslog4j = "1.0.0"
logstash-logback-encoder = "9.0"
mock-oauth2-server = "2.1.1"
mockk = "1.14.11"
sasGradlePlugins = "20260807.0944"
tbd-libs = "2026.01.22-09.16-1d3f6039"

[libraries]
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }
konfig = { module = "com.natpryce:konfig", version.ref = "konfig" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
ktor-server-call-id = { module = "io.ktor:ktor-server-call-id" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors" }
ktor-server-forwarded-header = { module = "io.ktor:ktor-server-forwarded-header" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-syslog4j = { module = "com.papertrailapp:logback-syslog4j", version.ref = "logback-syslog4j" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash-logback-encoder" }
mock-oauth2-server = { module = "no.nav.security:mock-oauth2-server", version.ref = "mock-oauth2-server" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
tbd-libs-azure-token-client-default = { module = "com.github.navikt.tbd-libs:azure-token-client-default", version.ref = "tbd-libs" }
tbd-libs-speed-client = { module = "com.github.navikt.tbd-libs:speed-client", version.ref = "tbd-libs" }
tbd-libs-spurtedu-client = { module = "com.github.navikt.tbd-libs:spurtedu-client", version.ref = "tbd-libs" }

[plugins]
sas-deployable = { id = "no.nav.helse.sas.sas-deployable", version.ref = "sasGradlePlugins" }
sas-root = { id = "no.nav.helse.sas.sas-root", version.ref = "sasGradlePlugins" }
