apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spanner
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spanner.intern.dev.nav.no
    - https://spanner.ansatt.dev.nav.no
  liveness:
    initialDelay: 10
    path: internal/isalive
  readiness:
    initialDelay: 10
    path: internal/isready
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  azure:
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/**
    application:
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c" # tbd
          - id: "c0227409-2085-4eb2-b487-c4ba270986a3" # nais-tbd
          - id: "5206a646-a99e-4cd5-90e4-758cf7948cc8" # flex
          - id: "317665ad-1402-458e-b8e6-9cb50afc1252" # speil-brukere-dev
      allowAllUsers: false
  accessPolicy:
    outbound:
      rules:
        - application: speed-api-dev-proxy
        - application: spleis-api
        - application: sparsom-api
        - application: spurtedu
  secureLogs:
    enabled: true
  env:
    - name: DEVELOPMENT
      value: "false"
    - name: SPLEIS_SCOPE
      value: api://dev-gcp.tbd.spleis-api/.default
    - name: SPARSOM_SCOPE
      value: api://dev-gcp.tbd.sparsom-api/.default
    - name: HTTP_PORT
      value: "8080"
    - name: HTTP_HOST
      value: spanner.ansatt.dev.nav.no
    - name: SPLEIS_API_URL
      value: http://spleis-api
    - name: SPARSOM_API_URL
      value: http://sparsom-api
    - name: SPURTE_DU_TILGANG
      value: "c0227409-2085-4eb2-b487-c4ba270986a3,5206a646-a99e-4cd5-90e4-758cf7948cc8,317665ad-1402-458e-b8e6-9cb50afc1252"
    - name: SPEED_API_URL
      value: http://speed-api-dev-proxy
    - name: TOKEN_ENDPOINT_ENV_KEY
      value: SPEED_API_DEV_PROXY_TOKEN_ENDPOINT
    - name: SPEED_API_DEV_PROXY_TOKEN_ENDPOINT
      value: http://speed-api-dev-proxy/token
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
