apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spanner
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://spanner.dev.intern.nav.no
  liveness:
    failureThreshold: 10
    initialDelay: 20
    path: internal/isalive
    timeout: 1
  readiness:
    initialDelay: 20
    path: internal/isready
    timeout: 1
  replicas:
    cpuThresholdPercentage: 90
    max: 1
    min: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  azure:
    application:
      tenant: nav.no
      enabled: true
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "f787f900-6697-440d-a086-d5bb56e26a9c"
          - id: "5206a646-a99e-4cd5-90e4-758cf7948cc8" #flex
      replyURLs:
        - "https://spanner.dev.intern.nav.no/oauth2/callback"
      allowAllUsers: false
  accessPolicy:
    outbound:
      rules:
        - application: spleis-api
          namespace: tbd
          cluster: dev-gcp
        - application: sparsom-api
          namespace: tbd
          cluster: dev-gcp
  secureLogs:
    enabled: true
  env:
    - name: DEVELOPMENT
      value: "false"
    - name: SPLEIS_CLIENT_ID
      value: api://dev-gcp.tbd.spleis-api/.default
    - name: SPARSOM_CLIENT_ID
      value: api://dev-gcp.tbd.sparsom-api/.default
    - name: HTTP_PORT
      value: "8080"
    - name: HTTP_HOST
      value: spanner.dev.intern.nav.no
    - name: SPLEIS_API_URL
      value: http://spleis-api
    - name: SPARSOM_API_URL
      value: http://sparsom-api
